FROM nginx:latest
COPY ./index.html /usr/share/nginx/html

# WORKDIR /src
# COPY ./ /src
# CMD ["docker", "run", "-it", "-p", "8080:80", "--name", "mynginx1",\
#  "-v", "~/src:/usr/share/nginx/html", "-d", "nginx"]
